2 4057 2019-3-22 17:27:37.323#saida_testar#$ python3 main.py SyntaxError: invalid syntax
1 4057 2019-5-2 22:16:26.294#dica_bullet#NameError: name 'NOME_DA_VARIAVEL' is not defined
1 4057 2019-3-22 15:30:43.997#dica_bullet#SyntaxError: invalid syntax
2 4057 2019-3-22 15:30:44.301#saida_testar#$ python3 main.py SyntaxError: invalid syntax
3 4057 2019-3-22 15:30:59.970#dica_open#SyntaxError: invalid syntax
4 4057 2019-3-22 15:31:01.735#dica_close#
sequencia